version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "sunday"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps"
    rebase-strategy: "auto"
    groups:
      cargo-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "sunday"
    commit-message:
      prefix: "ci"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
