[package]
name = "nexusd"
version = "0.4.1"
edition = "2021"
description = "Nexus daemon"
homepage = "https://github.com/pubky/pubky-nexus"
repository = "https://github.com/pubky/pubky-nexus"
license = "MIT"

[dependencies]
async-trait = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
cron = { workspace = true }
futures = { workspace = true }
nexus-webapi = { version = "0.4.1", path = "../nexus-webapi" }
nexus-common = { version = "0.4.1", path = "../nexus-common" }
opentelemetry = { workspace = true }
redis = { workspace = true, features = ["tokio-comp"] }
nexus-watcher = { version = "0.4.1", path = "../nexus-watcher" }
pubky-watcher = { version = "0.1.0", path = "../pubky-watcher" }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
anyhow = { workspace = true }
tokio-shared-rt = { workspace = true }
tempfile = { workspace = true }
tracing-test = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["testing"] }
