[package]
name = "nexus-common"
version = "0.4.1"
edition = "2021"
description = "Nexus common utils"
homepage = "https://github.com/pubky/pubky-nexus"
repository = "https://github.com/pubky/pubky-nexus"
license = "MIT"

[features]
test-utils = []

[dependencies]
async-trait = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
neo4rs = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-appender-tracing = "0.32.0"
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic"] }
opentelemetry_sdk = { workspace = true }
pubky = { workspace = true }
pubky-app-specs = { workspace = true }
pubky-watcher = { workspace = true }
redis = { workspace = true, features = ["tokio-comp", "json"] }
deadpool-redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = "1.0.7"
tracing = { workspace = true }
tracing-log = "0.2"
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio-shared-rt = { workspace = true }
tracing-test = { workspace = true }
