name: Lint

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: x86_64-unknown-linux-gnu

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "lint"
          cache-on-failure: true

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings # Fail on clippy warnings (main code, tests and benches)
